[features]
# Treat warnings as a build error.
strict = []
mpi = ["dep:mpi", "dep:superslice", "dep:memoffset", "dep:mpi-sys", "rlst/mpi"]

[package]
name = "kifmm"
version = "3.0.0-dev"
edition = "2021"
authors = ["Srinath Kailasa <srinathkailasa@gmail.com>"]
description = "Kernel-independent fast multipole method"
license = "BSD-3-Clause"
homepage = "https://github.com/bempp/kifmm"
repository = "https://github.com/bempp/kifmm"
readme = "README.md"
keywords = ["numerics"]
categories = ["mathematics", "science"]

[lib]
name = "kifmm"
crate-type = ["cdylib", "lib"]

[dependencies]
itertools = "0.14.*"
num = "0.4"
rayon = "1.11"
rand = "0.9.2"
kifmm-fftw-sys = { path = "../fftw-sys" }
green-kernels = { git = "https://github.com/bempp/green-kernels.git" }
lazy_static = "1.5.0"
num-complex = "0.4.6"
mpi = { git = "https://github.com/rsmpi/rsmpi.git", optional = true, features = ["complex"]}
mpi-sys = { git = "https://github.com/rsmpi/rsmpi.git", optional = true }
memoffset = {version = "0.9.1", optional = true}
pulp = "0.22"
bytemuck = "1.24.0"
superslice = {version = "1.0.0", optional = true}
rand_distr = "0.5.1"
rlst = { git = "https://github.com/linalg-rs/rlst.git" }

serde_yaml = "0.9.34"
coe-rs = "0.1.2"

[dev-dependencies]
approx = "0.5"
criterion = { version = "0.7.*", features = ["html_reports"]}

[build-dependencies]
cbindgen = "0.29"
cc = "1.2"

[[bench]]
name = "laplace"
harness = false

[[bench]]
name = "direct"
harness = false

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]

[lints.clippy]
wildcard_imports = "forbid"

[[example]]
name = "helmholtz"
doc-scrape-examples = true

[[example]]
name = "laplace"
doc-scrape-examples = true

[[example]]
name = "laplace_variable_expansion"
doc-scrape-examples = true

[[example]]
name = "mpi_test_attach_charges_ordered"
required-features = ["mpi"]

[package.metadata.example.mpi_test_attach_charges_ordered.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_attach_charges_unordered"
required-features = ["mpi"]

[package.metadata.example.mpi_test_attach_charges_unordered.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_fmm_gradients"
required-features = ["mpi"]

[package.metadata.example.mpi_test_fmm_gradients.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_fmm"
required-features = ["mpi"]

[package.metadata.example.mpi_test_fmm.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_layout"
required-features = ["mpi"]

[package.metadata.example.mpi_test_layout.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_p2m"
required-features = ["mpi"]

[package.metadata.example.mpi_test_p2m.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_sort"
required-features = ["mpi"]

[package.metadata.example.mpi_test_sort.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_trees"
required-features = ["mpi"]

[package.metadata.example.mpi_test_trees.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_test_upward_pass"
required-features = ["mpi"]

[package.metadata.example.mpi_test_upward_pass.templated-examples]
command = "mpirun -n {{NPROCESSES}}"

[[example]]
name = "mpi_tree"
required-features = ["mpi"]

[package.metadata.example.mpi_tree.templated-examples]
command = "mpirun -n {{NPROCESSES}}"
