[features]
# Treat warnings as a build error.
strict = []
mpi = ["dep:mpi", "dep:superslice", "dep:memoffset"]
python = ["dep:pyo3", "dep:numpy", "dep:blas-src", "dep:lapack-src"]

[package]
name = "kifmm"
version = "0.1.0-dev"
edition = "2021"
authors = ["Srinath Kailasa <srinathkailasa@gmail.com>"]
description = "Kernel-independent fast multipole method"
license = "BSD-3-Clause"
homepage = "https://github.com/bempp/kifmm"
repository = "https://github.com/bempp/kifmm"
readme = "README.md"
keywords = ["numerics"]
categories = ["mathematics", "science"]

[lib]
name = "kifmm"
crate-type = ["cdylib", "lib"]

[dependencies]
itertools = "0.13.*"
num = "0.4"
approx = "0.5"
rayon = "1.9"
rand = "0.8.5"
kifmm-fftw-sys = { path = "../fftw-sys" }
green-kernels = { git = "https://github.com/skailasa/green-kernels.git", branch = "simd"}
lazy_static = "1.4.0"
num-complex = "0.4.5"
mpi = { version = "0.8.*", optional = true}
memoffset = {version = "0.9.1", optional = true}
superslice = {version = "1.0.0", optional = true}
pyo3 = { version =  "0.21.2", features = ["extension-module", "multiple-pymethods"] , optional = true }
numpy = { version = "0.21", optional = true }
pulp = "0.18.12"
bytemuck = "1.16.0"
rand_distr = "0.4.3"
bitflags = "2.6.0"

[target.aarch64-apple-darwin.dependencies]
rlst = { git = "https://github.com/skailasa/rlst.git", branch = "simd", features = ["metal"]}
blas-src = { version = "0.10", features = ["accelerate"], optional = true }
lapack-src = { version = "0.10", features = ["accelerate"], optional = true }

[target.x86_64-unknown-linux-gnu.dependencies]
rlst = { git = "https://github.com/skailasa/rlst.git", branch = "simd"}
blas-src = { version = "0.10", features = ["openblas"], optional = true}
lapack-src = { version = "0.10", features = ["openblas"], optional = true}

[dev-dependencies]
criterion = { version = "0.5.*", features = ["html_reports"]}
csv = "1.3.0"
num_cpus = "1.16.0"

[[bench]]
name = "precomputation_f32"
harness = false

[[bench]]
name = "precomputation_f64"
harness = false

[[bench]]
name = "direct_f32"
harness = false

[[bench]]
name = "direct_f64"
harness = false

[[bench]]
name = "laplace_f32"
harness = false

[[bench]]
name = "laplace_f64"
harness = false


[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]

[target.aarch64-apple-darwin.dev-dependencies]
blas-src = { version = "0.10", features = ["accelerate"]}
lapack-src = { version = "0.10", features = ["accelerate"]}

[target.x86_64-unknown-linux-gnu.dev-dependencies]
blas-src = { version = "0.10", features = ["openblas"]}
lapack-src = { version = "0.10", features = ["openblas"]}

[lints.clippy]
wildcard_imports = "forbid"