language = "C"

[export]
exclude = ["ALPHA_INNER", "ALPHA_OUTER", "FFTW_ESTIMATE", "P2M_MAX_BLOCK_SIZE", "M2M_MAX_BLOCK_SIZE", "L2L_MAX_BLOCK_SIZE", "DEFAULT_NCRIT", "DEFAULT_M2L_FFT_BLOCK_SIZE", "DEEPEST_LEVEL", "LEVEL_SIZE", "LEVEL_DISPLACEMENT", "LEVEL_MASK", "BYTE_MASK", "BYTE_DISPLACEMENT", "NINE_BIT_MASK", "NSIBLINGS", "NSIBLINGS_SQUARED", "NCORNERS", "NTRANSFER_VECTORS_KIFMM", "NHALO"]


[enum]
prefix_with_name = true