[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "kifmm_py"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = ["numpy>=1.26.4"]

[tool.maturin]
python-source = "python"
module-name = "kifmm_py.kifmm_rust"
