[package]
name = "kifmm-fftw-src"
description = "FFTW src"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"
links="fftw3"
repository="https://github.com/bempp/kifmm"

[dependencies]

[build-dependencies]
cc = "1.0.90"
fs_extra = "1.3.0"
ftp = "3.0.1"
zip = "1.1.1"
