[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
kifmm ={ path = "../kifmm", features = ["mpi"]}
itertools = "0.14.*"
green-kernels = { git = "https://github.com/bempp/green-kernels.git"}
rlst = { git = "https://github.com/linalg-rs/rlst.git"}
rand = "0.9.2"
num = "0.4"
csv = "1.4.0"
mpi = { git = "https://github.com/rsmpi/rsmpi.git", optional = true}
rayon = "1.11"
clap = { version = "4.5.53", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
blas-src = { version = "0.14", features = ["accelerate"]}
lapack-src = { version = "0.13", features = ["accelerate"]}

[target.'cfg(target_os = "linux")'.dependencies]
lapack-src = { version = "0.13", features = ["netlib"]}
blas-src = { version = "0.14", features = ["blis"] }

[features]
mpi = ["kifmm/mpi", "dep:mpi", "rlst/mpi"]

[[bin]]
name = "grid_search_single_node"
path = "src/bin/grid_search_single_node.rs"
required-features = []

[[bin]]
name = "fmm_m2l_fft_mpi_f32"
path = "src/bin/fmm_m2l_fft_mpi_f32.rs"
required-features = ["mpi"]

[[bin]]
name = "fmm_m2l_blas_mpi_f32"
path = "src/bin/fmm_m2l_blas_mpi_f32.rs"
required-features = ["mpi"]
