name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  run-tests-rust:
    name: Run Rust tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable"]
        mpi: ['mpich', 'openmpi']
        feature-flags: ['--features "strict"']
    steps:
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt
      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Install cargo-mpirun and cargo-templated-examples
        run: cargo install cargo-mpirun cargo-templated-examples --force
      - name: Install Blas
        run: sudo apt-get install -y libopenblas-dev

      - uses: actions/checkout@v3
      - name: Run unit tests
        run: cargo test ${{ matrix.feature-flags }}
      - name: Run unit tests in release mode
        run: cargo test --release ${{ matrix.feature-flags }}
      - name: Run tests
        run: cargo test --examples --release ${{ matrix.feature-flags }}
      - name: Test benchmarks build
        run: cargo bench --no-run ${{ matrix.feature-flags }}
      - name: Run examples
        run: cargo templated-examples NPROCESSES 2,4
